### ISSUE TITLE
django 3.1: JSONField deprecation warning

### ISSUE THREAD

**Issue by tony** [python-social-auth/social-app-django#265]
I will update with a PR

`django.contrib.postgres.fields.JSONField` raises a deprecation warning in 3.1, and will be removed completely in 4.0.

See [Django 3.1 Release Notes](https://docs.djangoproject.com/en/3.1/releases/3.1/), section [JSONField for all supported database backends¶
](https://docs.djangoproject.com/en/3.1/releases/3.1/#jsonfield-for-all-supported-database-backends)

https://github.com/python-social-auth/social-app-django/blob/3e42f96fa68fda39c584bc2453faed0357c93720/social_django/fields.py#L12

#### CLI Warning

```
WARNINGS:
social_django.Partial.data: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
        HINT: Use django.db.models.JSONField instead.
social_django.UserSocialAuth.extra_data: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
        HINT: Use django.db.models.JSONField instead.
```

![image](https://user-images.githubusercontent.com/26336/89406669-2121b980-d6e3-11ea-9be3-b3def3ce54c9.png)
